### ISSUE TITLE
Get a list of available wifi connections

### ISSUE THREAD

**Issue by DenScheu** [smarthome-lab/hotspot-app#3]
Click on a button and show all available Wifi-networks in the surroundings.

![scanforwifi1](https://user-images.githubusercontent.com/38128307/39694609-31a8fa52-51e8-11e8-89f4-5b04e87b93a4.png)

![scanforwifi](https://user-images.githubusercontent.com/38128307/39676824-1ccfdb90-5171-11e8-92e5-d3b36aad1ab6.png)

**Comment by deniz-scheuring-aracom** [comment]
Check permissions during runtime

![problemdynamicpermissions](https://user-images.githubusercontent.com/38128307/39676830-3e9a0e8a-5171-11e8-8c65-0304d83eb642.png)
