### ISSUE TITLE
Display the Wifi-List from the Raspberry Pi

### ISSUE THREAD

**Issue by DenScheu** [smarthome-lab/hotspot-app#5]
**Description**

All available network connections from the Pi should be displayed in a list, so that you can choose one the raspberry Pi should connect with.

**Blockers**

- [x] The pi can send a list to the smartphone.

**Sub-Tasks**

- [x] display the wifi list from #3 and make it clickable

**Acceptance criterias**

If the Wifi List is displayed on the screen.

**Comment by deniz-scheuring-aracom** [comment]
Added a button to the first screen to navigate to a second screen with a wifi List


![hotspotwithlist1](https://user-images.githubusercontent.com/38128307/40788761-17348f3a-64f1-11e8-95a8-372c0461b433.jpg)

![hotspotwithlist2](https://user-images.githubusercontent.com/38128307/40788763-175b4bde-64f1-11e8-9aed-43975d4b674f.jpg)
