### ISSUE TITLE
Connect the raspberry Pi with the wifi

### ISSUE THREAD

**Issue by DenScheu** [smarthome-lab/hotspot-app#6]
**Description**

fter a wifi was chosen in the previous step, now the specific wifi has to be displayed. You can type in the password for the network and click on "connect the Raspberry to Wifi". After that process a message of failure or success is displayed. You can also click on a back button, to choose another network or you can canel the whole process.

**Blockers**

none

**Sub-Tasks**

- [x] use the wifi List from #3 and try to connect to a Network (click on a network, display a window with an input field for a password (**done**).

- [x] send the password to the raspberry pi.

**Acceptance criterias**

If the Pi is recieving the password and can connect to the Wifi.

**Comment by deniz-scheuring-aracom** [comment]
![hotspotwithlist3](https://user-images.githubusercontent.com/38128307/40788849-494c29e2-64f1-11e8-9229-35d3b12ca7cc.jpg)
