### ISSUE TITLE
Projektbeschreibung

### ISSUE THREAD

**Issue by TimoPurzner** [smarthome-lab/hotspot-app#8]
Die Projektbeschreibung als PDF bitte kurz hochladen

**Comment by Bachiller** [comment]
[Projektbeschreibung.pdf](https://github.com/smarthome-lab/hotspot-app/files/2008621/Projektbeschreibung.pdf)

**Comment by deniz-scheuring-aracom** [comment]
[Projektbeschreibung_bearbeitet.pdf](https://github.com/smarthome-lab/hotspot-app/files/2055065/Projektbeschreibung_bearbeitet.pdf)

@matthiasmoerz @Wachiwi @ZeroSoulEater 

Die bearbeitete Grafik innerhalb der Projektbeschreibung (wie am 30.05. besprochen)

@Bachiller 

Ich habe die roten Ausnahmeszenarien ergänzt
